### ISSUE TITLE
compile with cython and cl with visual studio produces errors

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7644]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/compile-with-cython-and-cl-with-visual-s/10388621)._

---
I have a python 3.12 beta release that I'm testing.  The code works in python 3.11.2.  I tried compiling it using cython and then cl with visual studio, but I received errors.  Does visual studio not support this new release?

I have version 3.0.0b2 of cython and I ran the command  cython -3 --embed -o aws_pc_backup.c ..\..\src\python\aws_pc_backup_main.py

Then I run the command

cl /O2 /I"C:\\Users\\jschw\\AppData\\Local\\Programs\\Python\\Python312\\include\\" aws_pc_backup.c /link C:\\Users\\jschw\\AppData\\Local\\Programs\\Python\\Python312\\libs\\python312.lib

and I get the following output:

(prod3120) H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\Version 1.5\src\c_3120>cl /O2 /I"C:\\Users\\jschw\\AppData\\Local\\Programs\\Python\\Python312\\include\\" aws_pc_backup.c /link C:\\Users\\jschw\\AppData\\Local\\Programs\\Python\\Python312\\libs\\python312.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

aws_pc_backup.c
aws_pc_backup.c(25796): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25809): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25810): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25811): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25812): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25813): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25814): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25820): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25821): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25822): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25823): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25824): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(25825): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26826): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26827): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26828): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26829): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26830): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26831): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(26837): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27061): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27065): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27066): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27067): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27068): error C2039: 'curexc_value': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(27069): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(30905): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(30908): error C2039: 'curexc_traceback': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
aws_pc_backup.c(31181): error C2039: 'curexc_type': is not a member of '_ts'
C:\Users\jschw\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'

(prod3120) H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\Version 1.5\src\c_3120>

I'll attach the python code here:

[aws_pc_backup_main.py.txt](https://aka.ms/dc/file?name=B1da1895f60a14a899a19c097bf4e0cbe638219380773427248_aws_pc_backup_main.py.txt&tid=1da1895f60a14a899a19c097bf4e0cbe638219380773427248)

---
#### Feedback Bot on 6/11/2023, 06:04 PM: 

(private comment, text removed)

---
#### James Schwartz solved on 6/9/2023, 01:21 PM, 0 votes: 

<p>Please close this.  I figured out the problem.  I needed to upgrade my cython version.  Sorry.</p>
