### ISSUE TITLE
Python package management is completely dysfunctional after updating pip to 10.x

### ISSUE THREAD

**Issue by seva0stapenko** [Microsoft/PTVS#4556]
Apparently pip 10.x made pip.main() non public. Python package managements in PT4VS is relying on pip.main() while installing packages and package updates ( -c "import pip; pip.main()" install - U ...)
As soon as pip is updated, everything is broken. Any attempt to run pip results in "AttributeError: 'module' object has no attribute 'main'" error and nothing works.

More over, all package entries get duplicated after updating pip to 10.x.

Please, make PT4VS compatible with pip 10.x. In the interim a quick fix to block updating to 10.x would be helpful.

**Comment by huguesv** [comment]
https://github.com/Microsoft/PTVS/issues/4194

Thanks. It's fixed in 15.8. FYI you can get 15.8 Preview builds at https://visualstudio.microsoft.com/vs/preview/
